### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xinggaojian** [ChenSee/ChenPay#1]
一直报 访问出错 错误

**Comment by ChenSee** [comment]
代码截图看看，cookie设置了没 ？https://t.me/chenAirport 加群

**Comment by xinggaojian** [comment]
设置了cookie 需要翻墙吗 我这打不开加群地址

**Comment by xinggaojian** [comment]
`<?php
/**
 * 两个支付必须分开运行，demo只是作为演示
 * Created by PhpStorm.
 * User: Chen
 * Date: 2018/9/28 0028
 * Time: 下午 17:16
 */

include './vendor/autoload.php';
$AliCookie = '';
$WxCookie = 'pgv_pvi=7517662208; pgv_pvid=1312823120; pt2gguin=o0136911578; RK=oSg8CHogE9; ptcz=1676e227fb8695a4434ac21e300f1871ee0e2c8a3d35fe3880a8d27cda19aff9; ptui_loginuin=2762614724; o_cookie=136911578; pac_uid=1_136911578; pgv_info=ssid=s7104725539; tvfe_boss_uuid=728e2506aa6703d0; pgv_si=s9056742400; ptisp=; uin=o0136911578; skey=@rQ9DgzfXd; mm_lang=zh_CN; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; wxuin=12237015; webwxuvid=c8f978e8dd52cf755564f637fda7cf71ce0dff8b19345d9ca29b927dbd63b252149b50c4ad7d20a6316375011f26060b; last_wxuin=12237015; wxpluginkey=1541139482; refreshTimes=2; wxsid=744sGlZ1GjLQCmM7; webwx_data_ticket=gSc0VAjvGwmJ3CILDl1mdlWe; webwx_auth_ticket=CIsBEMLupy8agAHvljD75+CgfR26pN+1xaVL/5Npa5dXukntcXFRJjmykRivLKuUcZyyLPIBtLWHpfx1zEQFEwn8cq4EsD5gUrFo74ENXmaPDBIlfwjEAK00+qgv+xTsAuO4Ymv9GaOOujo6yygKM7AAqDysdinamoiIbN+S2xIsCdQcaDXXeQzikw==; login_frequency=2; wxloadtime=1541154636_expired';


$GLOBALS['WxSum'] = 1;
$GLOBALS['syncKey'] = false;
ChenPay\Pay::Listen(10, function () use ($WxCookie) {
    // time 现在时间此为订单生成时间 默认3分钟有效时间
    $data = [['fee' => 0.01, 'time' => time() + 3 * 60]];
    try {
        $run = (new ChenPay\WxPay($WxCookie))->getData('wx2.qq.com', $GLOBALS['syncKey'])->DataHandle();


        $GLOBALS['syncKey'] = $run->syncKey;
        foreach ($data as $item) {
            $order = $run->DataContrast($item['fee'], $item['time']);
            if ($order) echo $order . "1！\n";
            unset($order, $item);// 摧毁变量防止内存溢出
        }
        echo $GLOBALS['WxSum'] . "2\n";
        $GLOBALS['WxSum']++;
    } catch (\ChenPay\PayException\PayException $e) {
        echo json_encode($e->getMessage()) . "\n";
        unset($e);// 摧毁变量防止内存溢出
    }
    unset($run, $data);// 摧毁变量防止内存溢出
});`

**Comment by ChenSee** [comment]
需要composer install

**Comment by xinggaojian** [comment]
![image](https://user-images.githubusercontent.com/42838200/47912099-6a235900-ded2-11e8-941b-024ce83f4e6c.png)
翻译过来 是 访问出错
