### ISSUE TITLE
已本地运行成功,如何访问程序呢?

### ISSUE THREAD

**Issue by banduoba** [ChenSee/ChenPay#11]
如图,已运行,如何测试以及访问程序呢
![image](https://user-images.githubusercontent.com/4811366/53301904-9143d300-3893-11e9-8c1c-ef6c04dcd6e9.png)

**Comment by xhwsd** [comment]
给你支付宝账号 转账 0.01 啊~~
看程序流程逻辑是否成功啊~

**Comment by banduoba** [comment]
@xhwsd  没有前台页面么，在哪里生成订单，这个源码里面没看到这个逻辑，另外我直接转账了，终端没有看到获取到支付宝的转账信息

**Comment by xhwsd** [comment]
@banduoba 看看 README.md 的使用教程吧！

**Comment by banduoba** [comment]
@xhwsd 看了好久啊 完全按照 readme 操作的 不过怎么获取到支付宝付款信息的没看到

**Comment by banduoba** [comment]
@xhwsd 刚刚测试了下发现 支付宝付款备注123456 可以获取到终端输出,微信不行,没有任何输出,两个我是分别运行的

**Comment by ChenSee** [comment]
@banduoba 微信的监听log有没有？wx.qq.com可能要改成wx2.qq.com
