### ISSUE TITLE
getData一直获取不到新的消息

### ISSUE THREAD

**Issue by daojiAnime** [ChenSee/ChenPay#14]
我用python调用API，getData一直获取不到新消息，但是我请求的参数都是和PHP代码里面的一样的，作者能够给我一些帮助吗

**Comment by ChenSee** [comment]
![image](https://user-images.githubusercontent.com/11918919/56897341-e1702900-6ac0-11e9-9060-f4ba65b33193.png)
header这些需要模拟
服务器时间对的上吗？

**Comment by daojiAnime** [comment]
谢谢作者，我已经找到问题了，是SyncKey在初始化后我没有将获取消息返回的储存，并用它进行获取消息
