### ISSUE TITLE
试用了一下，发现微信支付和支付宝都没有检测到付款

### ISSUE THREAD

**Issue by billLiao** [ChenSee/ChenPay#16]
跟进 redeme 运行试了一下，微信支付和支付宝使用收款码都没有收到进账提示。
微信支付是发现网页版的微信不推送微信支付的提醒。支付宝的也没有收到提示。

**Comment by ChenSee** [comment]
自行修改订单生产时间，时区必须是中国时区

**Comment by billLiao** [comment]
要怎么修改呢，我用的是 test 里写的，3 分钟有效那个

**Comment by ChenSee** [comment]
订单创建时间time变量是个固定的值。可以改成当前时间戳+3分钟
