### ISSUE TITLE
支付宝订单接口返回乱码

### ISSUE THREAD

**Issue by lhalcyon** [ChenSee/ChenPay#17]
如题,https://mbillexprod.alipay.com/enterprise/tradeListQuery.json  这个接口,我用java调用后返回乱码, 请问?

**Comment by ChenSee** [comment]
需要转码好像

**Comment by lhalcyon** [comment]
我参考了PHP的代码
![image](https://user-images.githubusercontent.com/21357951/59284515-f5ea3880-8c9e-11e9-88df-9a565a724f0a.png) 用Java转码 ,但还是得不到要的结果.  用postman可以得到结果

**Comment by lhalcyon** [comment]
解决了,是gzip问题.
