### ISSUE TITLE
how can i install it?

### ISSUE THREAD

**Issue by githubphone** [ChenSee/ChenPay#19]
composer require chen-see/chen-pay

Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Using version ^1.2 for chen-see/chen-pay
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.

**Comment by ChenSee** [comment]
running "/usr/bin/composer self-update" ？
