### ISSUE TITLE
这个要是能顺手检测用户备注话就能高并发了

### ISSUE THREAD

**Issue by cmmdwl** [ChenSee/ChenPay#3]
这个要是能顺手检测用户备注话就能高并发了，随机生成一个数值让用户填入，简单还有效

**Comment by cmmdwl** [comment]
要不然话就只能选择刷新一个二维码并在里面填一个随机的收款理由了

**Comment by ChenSee** [comment]
可以  有时间 我会加个获取备注的变量 届时你可以判断。。

**Comment by ChenSee** [comment]
6142b6a36f3368f93112bf79838b451ec1487f86 @cmmdwl
