### ISSUE TITLE
這個錯誤，我覺得應該 是複製對的了。

### ISSUE THREAD

**Issue by vggh66** [ChenSee/ChenPay#5]
![qq 20181219205853](https://user-images.githubusercontent.com/35464331/50221778-3abca300-03d1-11e9-8646-deb835086794.png)

**Comment by ChenSee** [comment]
这样应该是没有对的。复制Cookie:后面所有的字符。你是复制的哪个截图看看。

**Comment by vggh66** [comment]
哦，這個圖。
![qq 20181219210908](https://user-images.githubusercontent.com/35464331/50222183-71df8400-03d2-11e9-9bd4-7e36901e9e27.png)

**Comment by ChenSee** [comment]
微信的话应该先注释掉支付宝的代码。
![image](https://user-images.githubusercontent.com/11918919/50222288-cf73d080-03d2-11e9-86f0-204cc441ab27.png)

**Comment by vggh66** [comment]
test.php就以下這點內容

<?php
/**
 * 两个支付必须分开运行，demo只是作为演示
 * Created by PhpStorm.
 * User: Chen
 * Date: 2018/9/28 0028
 * Time: 下午 17:16
 */
include __DIR__ . '/../vendor/autoload.php';

$WxCookie = 'pgv_pvi=3811391488; pt2gguin=o1440235506; RK=kpzlyPPQPb; ptcz=8b2bdc0b3421621381749c6c726712f53afb7dbc496b740fa8fdaa211a207d93; pgv_pvid=3826245339; o_cookie=1440235506; gr_user_id=80a44630-093c-4321-a954-7bbc153fa514; mm_lang=zh_TW; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; wxuin=419231880; webwxuvid=8868d3d766b94f2395a95b1b4a207fc593b1f5ed267ee020e8539958fe6d8c585fe2080964ea655cdf4ea155d654392f; last_wxuin=419231880; wxpluginkey=1545207482; wxsid=ZVnskETcBzI79YmU; webwx_data_ticket=gSc+cfoPXWteFVoAV87fAgcy; webwx_auth_ticket=CIsBEPPwuPgKGoABJHWPT/cZWAHNixFXpOBnnErw3oNFR8bEeB/mO404h6fabuVW+nKYsdRhGQXEkFuX23ninVmBARhRwlt+GjqG6qjI4+v+BmNec9N026huaI7aF2xiHQLB9GuvqkoC4Oge20Z1fz7Hhm/H6tYUX0iJAusoFGGoKQ1QWKsTyhr6ks0=; login_frequency=2; wxloadtime=1545223569_expired';
$GLOBALS['WxSum'] = 1;
$GLOBALS['syncKey'] = false;
ChenPay\Pay::Listen(10, function () use ($WxCookie) {
    // time 现在时间此为订单生成时间 默认3分钟有效时间
    $data = [['fee' => 0.01, 'time' => time() + 3 * 60]];
    try {
        $run = (new ChenPay\WxPay($WxCookie))->getData('wx2.qq.com', $GLOBALS['syncKey'])->DataHandle();
        $GLOBALS['syncKey'] = $run->syncKey;
        foreach ($data as $item) {
            $order = $run->DataContrast($item['fee'], $item['time']);
            if ($order) echo $order . "订单有效！\n";
            unset($order, $item);// 摧毁变量防止内存溢出
        }
        echo $GLOBALS['WxSum'] . "次运行\n";
        $GLOBALS['WxSum']++;
    } catch (\ChenPay\PayException\PayException $e) {
        echo $e->getMessage() . "\n";
        unset($e);// 摧毁变量防止内存溢出
    }
    unset($run, $data);// 摧毁变量防止内存溢出
});

**Comment by vggh66** [comment]
<?php
/**
 * 两个支付必须分开运行，demo只是作为演示
 * Created by PhpStorm.
 * User: Chen
 * Date: 2018/9/28 0028
 * Time: 下午 17:16
 */
include __DIR__ . '/../vendor/autoload.php';

$WxCookie = 'pgv_pvi=3811391488; pt2gguin=o1440235506; RK=kpzlyPPQPb; ptcz=8b2bdc0b3421621381749c6c726712f53afb7dbc496b740fa8fdaa211a207d93; pgv_pvid=3826245339; o_cookie=1440235506; gr_user_id=80a44630-093c-4321-a954-7bbc153fa514; mm_lang=zh_TW; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; wxuin=419231880; webwxuvid=8868d3d766b94f2395a95b1b4a207fc593b1f5ed267ee020e8539958fe6d8c585fe2080964ea655cdf4ea155d654392f; last_wxuin=419231880; wxpluginkey=1545207482; wxsid=ZVnskETcBzI79YmU; webwx_data_ticket=gSc+cfoPXWteFVoAV87fAgcy; webwx_auth_ticket=CIsBEPPwuPgKGoABJHWPT/cZWAHNixFXpOBnnErw3oNFR8bEeB/mO404h6fabuVW+nKYsdRhGQXEkFuX23ninVmBARhRwlt+GjqG6qjI4+v+BmNec9N026huaI7aF2xiHQLB9GuvqkoC4Oge20Z1fz7Hhm/H6tYUX0iJAusoFGGoKQ1QWKsTyhr6ks0=; login_frequency=2; wxloadtime=1545223569_expired';
$GLOBALS['WxSum'] = 1;
$GLOBALS['syncKey'] = false;
ChenPay\Pay::Listen(10, function () use ($WxCookie) {
    // time 现在时间此为订单生成时间 默认3分钟有效时间
    $data = [['fee' => 0.01, 'time' => time() + 3 * 60]];
    try {
        $run = (new ChenPay\WxPay($WxCookie))->getData('wx2.qq.com', $GLOBALS['syncKey'])->DataHandle();
        $GLOBALS['syncKey'] = $run->syncKey;
        foreach ($data as $item) {
            $order = $run->DataContrast($item['fee'], $item['time']);
            if ($order) echo $order . "订单有效！\n";
            unset($order, $item);// 摧毁变量防止内存溢出
        }
        echo $GLOBALS['WxSum'] . "次运行\n";
        $GLOBALS['WxSum']++;
    } catch (\ChenPay\PayException\PayException $e) {
        echo $e->getMessage() . "\n";
        unset($e);// 摧毁变量防止内存溢出
    }
    unset($run, $data);// 摧毁变量防止内存溢出
});

**Comment by vggh66** [comment]
怎麼複製的內容粘貼上不全

**Comment by ChenSee** [comment]
截图看看 test.php

**Comment by ChenSee** [comment]
空格怎么这么多。感觉是这个问题 你用什么编辑器的

**Comment by vggh66** [comment]
其實沒那麼多空格，我有點多此一舉了，粘貼到文本再截圖的。現在放另一組圖。
![qq 20181219215438](https://user-images.githubusercontent.com/35464331/50224367-bec65900-03d8-11e9-8c81-687dd6c3ef6d.png)
![qq 20181219215353](https://user-images.githubusercontent.com/35464331/50224369-bf5eef80-03d8-11e9-872a-8d6b6c5eabb9.png)

**Comment by ChenSee** [comment]
wx2.qq.com 改成wx.qq.com

**Comment by vggh66** [comment]
謝謝老大，這樣就解決了。
[root@host test]# php test.php
1次运行
2次运行
3次运行
4次运行
5次运行
6次运行
7次运行
不過現在點網頁上的充值顯示這個狀態。
![qq 20181219222303](https://user-images.githubusercontent.com/35464331/50225913-c556cf80-03dc-11e9-8aef-5e23abb632ea.png)

**Comment by ChenSee** [comment]
这个没配置对吧 仔细看readme

**Comment by vggh66** [comment]
好的，我先自己研究下，有困難在來麻煩你。

**Comment by banduoba** [comment]
@vggh66 运行之后本地如何访问啊 谢谢可以告知下么
