### ISSUE TITLE
遇到了比较尴尬的事情 超时了

### ISSUE THREAD

**Issue by cmmdwl** [ChenSee/ChenPay#6]
服务器没有被墙，在国内，推出支付宝后cook失效了
cURL error 28: Resolving timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
[root@cmmdwl test]# php test.php 
cURL error 28: Resolving timed out after 10000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
1次运行
2次运行
3次运行
4次运行
5次运行
6次运行
7次运行
8次运行
cURL error 28: Resolving timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
9次运行
cookie失效

**Comment by cmmdwl** [comment]
cookie失效是我手动退出帐号后的提示

**Comment by ChenSee** [comment]
这种情况估计是网络线路不好

**Comment by cmmdwl** [comment]
@chensee 问题来了，国内服务器不可能访问支付宝都出毛病吧。。。
难道是支付宝觉得这个ip不好封了？
这个问题是这次出现的，之前是重复订单有效
看起来你更新了一些东西，我更新下试试

**Comment by ChenSee** [comment]
有些服务器是会出现这种情况，或许是dns问题，也有可能是网络不好。总结就是网络不通畅导致。

**Comment by cmmdwl** [comment]
cURL error 28: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

cURL error 7: Failed to connect to enterpriseportal.alipay.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

看起来确实出现了连接问题。。。

**Comment by ChenSee** [comment]
换个服务器或许能绝决这个问题，之前我在vultr就是这个问题，极其不稳定。有时直接就访问不了alipay，搞得直接掉线了

**Comment by banduoba** [comment]
@cmmdwl 请问下运行之后 本地网站如何访问啊
