### ISSUE TITLE
呵呵，拼一拼，我这有个无限动态创建二维码接口

### ISSUE THREAD

**Issue by xhwsd** [ChenSee/ChenPay#8]
`alipays://platformapi/startapp?appId=09999988&actionType=toAccount&goBack=NO&amount=金额&userId=2088502951749002&memo=备注`
指定备注和金额并创建二维码，然后再监听收款。拼一拼，

userId=2088502951749002 需要用户的~

**Comment by cyueo** [comment]
@xhwsd ？？

**Comment by banduoba** [comment]
@xhwsd 在哪里啊你的项目

**Comment by xhwsd** [comment]
`alipays://platformapi/startapp?appId=20000123&actionType=scan&biz_data={"s": "money","u": "2088222129248934","a": "1.00","m":"2018121414041942631"}  要转编码哦 在常量的哦
alipays://platformapi/startapp?appId=20000123&actionType=scan&biz_data={"s": "money","u": "商户id","a": "金额","m":"备注"}  要转编码哦 在常量的哦
`
无限动态生成支付二维码码，然后PHP监视订单备注？

**Comment by xhwsd** [comment]
@banduoba 

`alipays://platformapi/startapp?appId=20000123&actionType=scan&biz_data={"s": "money","u": "2088222129248934","a": "1.00","m":"2018121414041942631"}

alipays://platformapi/startapp?appId=20000123&actionType=scan&biz_data={"s": "money","u": "商户id","a": "金额","m":"备注"}`

1. 商户ID 支付宝网页中提取
2. 注意要转编码
3. 无限动态生成支付二维码
4. 然后PHP监视订单备注

**Comment by banduoba** [comment]
@xhwsd 4. 然后PHP监视订单备注（如果实现，连挂机VPS 手机都不需要了，虚拟主机+定时任务~） 你这里实现了么, 这个要能获取到支付宝账单吧

**Comment by xhwsd** [comment]
@banduoba  
是的 获取支付宝 订单信息，并判断备注信息。
我没实现，我菜鸟....

**Comment by banduoba** [comment]
> @banduoba
> 是的 获取支付宝 订单信息，并判断备注信息。
> 我没写，菜鸟一枚....

支付宝的我用 python 可以实现 就是微信的没搞定呢

**Comment by xhwsd** [comment]
呵呵，微信暂时（我）还没发现类似的 无限生成二维码的接口，
市面上大部分都是手机安装自己的APK和微信，然后APK钩子微信动态创建二维码（指定备注）
要不就是 xx.01 xx.02  靠二维码金额去区分用户

**Comment by THROFHR** [comment]
目前结果：扫码进入转账，不能设置金额，和不设置金额的收款码一样效果，无法实现**无限动态创建二维码**
