### ISSUE TITLE
微信支付是否要求网页版微信一直在线？

### ISSUE THREAD

**Issue by zwx1231** [ChenSee/ChenPay#9]
网页版微信推出后，后台设置里的微信就自动关闭了。

**Comment by ChenSee** [comment]
不用 但是必须手机版在线

**Comment by zwx1231** [comment]
我是一直手机版在线，扫码登陆网页版之后复制了cookie。但是网页版一退出开关就自己关掉了。
/你的目录/storage/logs/chenpay.log。这里面也没有log文件。不知为何

**Comment by ChenSee** [comment]
手动运行尝试一下
